from enum import Enum


class ActionType(str, Enum):
    """Standardized vocabulary of auditable actions"""

    # Admin Actions (Priority 1)
    USER_CREATED = "user_created"
    USER_DELETED = "user_deleted"
    USER_UPDATED = "user_updated"
    ROLE_CREATED = "role_created"
    ROLE_MODIFIED = "role_modified"
    ROLE_DELETED = "role_deleted"
    PERMISSION_CHANGED = "permission_changed"
    TENANT_SETTINGS_UPDATED = "tenant_settings_updated"
    CREDENTIALS_UPDATED = "credentials_updated"
    FEDERATION_UPDATED = "federation_updated"
    API_KEY_GENERATED = "api_key_generated"
    MODULE_ADDED = "module_added"
    MODULE_ADDED_TO_TENANT = "module_added_to_tenant"

    # User Actions (Priority 2)
    ASSISTANT_CREATED = "assistant_created"
    ASSISTANT_DELETED = "assistant_deleted"
    ASSISTANT_UPDATED = "assistant_updated"
    ASSISTANT_TRANSFERRED = "assistant_transferred"
    ASSISTANT_PUBLISHED = "assistant_published"
    SPACE_CREATED = "space_created"
    SPACE_UPDATED = "space_updated"
    SPACE_DELETED = "space_deleted"
    SPACE_MEMBER_ADDED = "space_member_added"
    SPACE_MEMBER_REMOVED = "space_member_removed"
    APP_CREATED = "app_created"
    APP_DELETED = "app_deleted"
    APP_UPDATED = "app_updated"
    APP_EXECUTED = "app_executed"
    APP_PUBLISHED = "app_published"
    APP_RUN_DELETED = "app_run_deleted"
    SESSION_STARTED = "session_started"
    SESSION_ENDED = "session_ended"
    FILE_UPLOADED = "file_uploaded"
    FILE_DELETED = "file_deleted"
    WEBSITE_CREATED = "website_created"
    WEBSITE_UPDATED = "website_updated"
    WEBSITE_DELETED = "website_deleted"
    WEBSITE_CRAWLED = "website_crawled"
    WEBSITE_TRANSFERRED = "website_transferred"
    GROUP_CHAT_CREATED = "group_chat_created"
    COLLECTION_CREATED = "collection_created"
    COLLECTION_UPDATED = "collection_updated"
    COLLECTION_DELETED = "collection_deleted"
    INTEGRATION_ADDED = "integration_added"
    INTEGRATION_REMOVED = "integration_removed"
    INTEGRATION_CONNECTED = "integration_connected"
    INTEGRATION_DISCONNECTED = "integration_disconnected"
    INTEGRATION_KNOWLEDGE_CREATED = "integration_knowledge_created"
    INTEGRATION_KNOWLEDGE_DELETED = "integration_knowledge_deleted"
    INTEGRATION_KNOWLEDGE_SYNCED = "integration_knowledge_synced"
    COMPLETION_MODEL_UPDATED = "completion_model_updated"
    EMBEDDING_MODEL_UPDATED = "embedding_model_updated"
    TRANSCRIPTION_MODEL_UPDATED = "transcription_model_updated"
    IMAGE_GENERATION_MODEL_UPDATED = "image_generation_model_updated"
    TEMPLATE_CREATED = "template_created"
    TEMPLATE_UPDATED = "template_updated"
    TEMPLATE_DELETED = "template_deleted"

    # Security Classification Actions
    SECURITY_CLASSIFICATION_CREATED = "security_classification_created"
    SECURITY_CLASSIFICATION_UPDATED = "security_classification_updated"
    SECURITY_CLASSIFICATION_DELETED = "security_classification_deleted"
    SECURITY_CLASSIFICATION_LEVELS_UPDATED = "security_classification_levels_updated"
    SECURITY_CLASSIFICATION_ENABLED = "security_classification_enabled"
    SECURITY_CLASSIFICATION_DISABLED = "security_classification_disabled"

    # MCP Server Actions
    MCP_SERVER_CREATED = "mcp_server_created"
    MCP_SERVER_UPDATED = "mcp_server_updated"
    MCP_SERVER_DELETED = "mcp_server_deleted"
    MCP_SERVER_ENABLED = "mcp_server_enabled"
    MCP_SERVER_DISABLED = "mcp_server_disabled"
    MCP_SERVER_TOOL_ENABLED = "mcp_server_tool_enabled"
    MCP_SERVER_TOOL_DISABLED = "mcp_server_tool_disabled"

    # System Actions
    RETENTION_POLICY_APPLIED = "retention_policy_applied"
    ENCRYPTION_KEY_ROTATED = "encryption_key_rotated"
    SYSTEM_MAINTENANCE = "system_maintenance"

    # Audit Access Actions
    AUDIT_SESSION_CREATED = "audit_session_created"
    AUDIT_LOG_VIEWED = "audit_log_viewed"
    AUDIT_LOG_EXPORTED = "audit_log_exported"
